"use client"

import React from 'react';
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from '@/components/ui/tooltip';

// Mapeamento de ícones Lucide para Material Icons seguindo Material Design, Nielsen e WCAG 2.2 AA
export const IconMapping = {
  // Navegação e Interface
  'home': 'home',
  'user': 'person',
  'settings': 'settings',
  'menu': 'menu',
  'search': 'search',
  'filter': 'filter_list',
  'sort': 'sort',
  'refresh': 'refresh',
  'close': 'close',
  'check': 'check',
  'plus': 'add',
  'plus-circle': 'add_circle',
  'minus': 'remove',
  'edit': 'edit',
  'delete': 'delete',
  'trash': 'delete',
  'trash-2': 'delete',
  'save': 'save',
  'download': 'download',
  'upload': 'upload',
  'copy': 'content_copy',
  'external-link': 'open_in_new',
  'log-out': 'logout',
  'rotate-ccw': 'refresh',
  'type': 'text_fields',
  'contrast': 'contrast',
  'zap': 'flash_on',
  'keyboard': 'keyboard',
  'refresh-cw': 'refresh',
  'sparkles': 'auto_awesome',
  
  // Financeiro
  'dollar-sign': 'attach_money',
  'credit-card': 'credit_card',
  'wallet': 'account_balance_wallet',
  'trending-up': 'trending_up',
  'trending-down': 'trending_down',
  'chart': 'bar_chart',
  'bar-chart-3': 'bar_chart',
  'pie-chart': 'pie_chart',
  'calculator': 'calculate',
  'receipt': 'receipt',
  'piggy-bank': 'savings',
  'target': 'flag',
  
  // IA e Tecnologia
  'brain': 'psychology',
  'cpu': 'memory',
  'database': 'storage',
  'server': 'dns',
  'cloud': 'cloud',
  
  // Alertas e Notificações
  'bell': 'notifications',
  'bell-ring': 'notifications_active',
  'alert-triangle': 'warning',
  'alert-circle': 'error',
  'info': 'info',
  'check-circle': 'check_circle',
  'x-circle': 'cancel',
  'clock': 'schedule',
  'calendar': 'calendar_today',
  'calendar-days': 'event',
  
  // Segurança
  'shield': 'security',
  'shield-check': 'verified_user',
  'shield-alert': 'security',
  'lock': 'lock',
  'unlock': 'lock_open',
  'key': 'vpn_key',
  'fingerprint': 'fingerprint',
  
  // Formulários e Inputs
  'mail': 'mail',
  'eye': 'visibility',
  'eye-off': 'visibility_off',
  'phone': 'phone',
  'map-pin': 'location_on',
  'globe': 'language',
  'flag': 'flag',
  
  // Alertas e Notificações
  'bell': 'notifications',
  'bell-ring': 'notifications_active',
  'alert-triangle': 'warning',
  'alert-circle': 'error',
  'info': 'info',
  'check-circle': 'check_circle',
  'x-circle': 'cancel',
  'clock': 'schedule',
  'calendar': 'calendar_today',
  'calendar-days': 'event',
  
  // Formulários e Inputs
  'mail': 'mail',
  'lock': 'lock',
  'eye': 'visibility',
  'eye-off': 'visibility_off',
  'key': 'vpn_key',
  'phone': 'phone',
  'map-pin': 'location_on',
  'globe': 'language',
  'flag': 'flag',
  
  // Ações e Estados
  'play': 'play_arrow',
  'pause': 'pause',
  'stop': 'stop',
  'skip-forward': 'skip_next',
  'skip-back': 'skip_previous',
  'chevron-up': 'keyboard_arrow_up',
  'chevron-down': 'keyboard_arrow_down',
  'chevron-left': 'keyboard_arrow_left',
  'chevron-right': 'keyboard_arrow_right',
  'arrow-up': 'arrow_upward',
  'arrow-down': 'arrow_downward',
  'arrow-left': 'arrow_back',
  'arrow-right': 'arrow_forward',
  
  // Arquivos e Documentos
  'file': 'description',
  'file-text': 'article',
  'file-plus': 'note_add',
  'folder': 'folder',
  'folder-plus': 'create_new_folder',
  'folder-open': 'folder_open',
  'archive': 'archive',
  'bookmark': 'bookmark',
  'bookmark-plus': 'bookmark_add',
  
  // Comunicação
  'message': 'message',
  'message-circle': 'chat',
  'mail': 'mail',
  'send': 'send',
  'reply': 'reply',
  'share': 'share',
  'link': 'link',
  
  // Status e Indicadores
  'loading': 'hourglass_empty',
  'spinner': 'refresh',
  'star': 'star',
  'star-filled': 'star',
  'heart': 'favorite',
  'heart-filled': 'favorite',
  'thumbs-up': 'thumb_up',
  'thumbs-down': 'thumb_down',
  'like': 'thumb_up',
  'dislike': 'thumb_down',
  
  // Categorias e Organização
  'tag': 'local_offer',
  'tags': 'local_offer',
  'category': 'category',
  'grid': 'grid_view',
  'list': 'list',
  'layout': 'view_module',
  'columns': 'view_column',
  'rows': 'view_list',
  
  // Segurança e Privacidade
  'shield': 'security',
  'shield-check': 'verified_user',
  'shield-alert': 'security',
  'lock': 'lock',
  'unlock': 'lock_open',
  'key': 'vpn_key',
  'fingerprint': 'fingerprint',
  
  // Acessibilidade
  'accessibility': 'accessibility_new',
  'accessible': 'accessible',
  'volume': 'volume_up',
  'volume-off': 'volume_off',
  'volume-low': 'volume_down',
  'volume-high': 'volume_up',
  'mic': 'mic',
  'mic-off': 'mic_off',
  'video': 'videocam',
  'video-off': 'videocam_off',
  'camera': 'camera_alt',
  'image': 'image',
  'palette': 'palette',
  'contrast': 'contrast',
  'brightness': 'brightness_6',
  
  // Utilitários
  'help': 'help',
  'help-circle': 'help_outline',
  'question': 'help_outline',
  'info': 'info',
  'more': 'more_horiz',
  'more-vertical': 'more_vert',
  'dots': 'more_horiz',
  'dots-vertical': 'more_vert',
  'ellipsis': 'more_horiz',
  'ellipsis-vertical': 'more_vert',
  
  // Tempo e Data
  'time': 'access_time',
  'clock': 'schedule',
  'calendar': 'calendar_today',
  'calendar-plus': 'event_available',
  'calendar-minus': 'event_busy',
  'timer': 'timer',
  'stopwatch': 'timer',
  'hourglass': 'hourglass_empty',
  
  // Direções e Navegação
  'compass': 'explore',
  'navigation': 'navigation',
  'map': 'map',
  'location': 'location_on',
  'pin': 'room',
  'target': 'flag',
  'crosshair': 'gps_fixed',
  
  // Tecnologia
  'wifi': 'wifi',
  'wifi-off': 'wifi_off',
  'bluetooth': 'bluetooth',
  'bluetooth-off': 'bluetooth_disabled',
  'battery': 'battery_std',
  'battery-charging': 'battery_charging_full',
  'power': 'power',
  'plug': 'power',
  'cpu': 'memory',
  'hard-drive': 'storage',
  'database': 'storage',
  'server': 'dns',
  'cloud': 'cloud',
  'cloud-upload': 'cloud_upload',
  'cloud-download': 'cloud_download',
  'cloud-off': 'cloud_off',
  
  // Social e Pessoas
  'users': 'group',
  'user-plus': 'person_add',
  'user-minus': 'person_remove',
  'user-check': 'person_check',
  'user-x': 'person_off',
  'team': 'groups',
  'organization': 'business',
  'building': 'business',
  'company': 'business',
  
  // Comércio e Vendas
  'shopping-cart': 'shopping_cart',
  'shopping-bag': 'shopping_bag',
  'store': 'store',
  'shop': 'storefront',
  'barcode': 'qr_code',
  'qr-code': 'qr_code',
  'price-tag': 'local_offer',
  'discount': 'local_offer',
  'percent': 'percent',
  'gift': 'card_giftcard',
  'truck': 'local_shipping',
  'package': 'inventory',
  'box': 'inventory_2',
  
  // Educação e Aprendizado
  'book': 'book',
  'book-open': 'menu_book',
  'graduation-cap': 'school',
  'award': 'emoji_events',
  'certificate': 'workspace_premium',
  'trophy': 'emoji_events',
  'medal': 'workspace_premium',
  'badge': 'workspace_premium',
  
  // Saúde e Medicina
  'heart': 'favorite',
  'heartbeat': 'favorite',
  'activity': 'trending_up',
  'pulse': 'favorite',
  'thermometer': 'thermostat',
  'droplet': 'water_drop',
  'pill': 'medication',
  'syringe': 'medication',
  'stethoscope': 'medical_services',
  'cross': 'medical_services',
  
  // Esportes e Lazer
  'gamepad': 'sports_esports',
  'controller': 'sports_esports',
  'football': 'sports_soccer',
  'basketball': 'sports_basketball',
  'tennis': 'sports_tennis',
  'golf': 'sports_golf',
  'swimming': 'pool',
  'running': 'directions_run',
  'cycling': 'directions_bike',
  'hiking': 'hiking',
  
  // Música e Entretenimento
  'music': 'music_note',
  'play': 'play_arrow',
  'pause': 'pause',
  'stop': 'stop',
  'skip-forward': 'skip_next',
  'skip-back': 'skip_previous',
  'repeat': 'repeat',
  'shuffle': 'shuffle',
  'volume': 'volume_up',
  'mic': 'mic',
  'headphones': 'headphones',
  'speaker': 'speaker',
  
  // Casa e Lar
  'home': 'home',
  'house': 'home',
  'building': 'business',
  'door': 'door_front_door',
  'window': 'window',
  'key': 'vpn_key',
  'lock': 'lock',
  'unlock': 'lock_open',
  'bed': 'bed',
  'bath': 'bathtub',
  'kitchen': 'kitchen',
  'living-room': 'chair',
  'garage': 'garage',
  'garden': 'yard',
  'pool': 'pool',
  
  // Transporte
  'car': 'directions_car',
  'truck': 'local_shipping',
  'bus': 'directions_bus',
  'train': 'train',
  'plane': 'flight',
  'ship': 'directions_boat',
  'bike': 'directions_bike',
  'motorcycle': 'motorcycle',
  'taxi': 'local_taxi',
  'subway': 'subway',
  
  // Clima e Natureza
  'sun': 'wb_sunny',
  'moon': 'nightlight_round',
  'cloud': 'cloud',
  'cloud-rain': 'grain',
  'cloud-snow': 'ac_unit',
  'cloud-lightning': 'flash_on',
  'wind': 'air',
  'droplet': 'water_drop',
  'snowflake': 'ac_unit',
  'thermometer': 'thermostat',
  'umbrella': 'umbrella',
  'tree': 'park',
  'flower': 'local_florist',
  'leaf': 'park',
  'mountain': 'landscape',
  'waves': 'waves',
  
  // Comida e Bebida
  'coffee': 'coffee',
  'wine': 'wine_bar',
  'beer': 'sports_bar',
  'cake': 'cake',
  'pizza': 'local_pizza',
  'hamburger': 'lunch_dining',
  'ice-cream': 'icecream',
  'apple': 'apple',
  'banana': 'apple',
  'carrot': 'apple',
  'bread': 'bakery_dining',
  'fish': 'set_meal',
  'chicken': 'set_meal',
  'beef': 'set_meal',
  'egg': 'egg',
  'milk': 'local_drink',
  'water': 'water_drop',
  'juice': 'local_drink',
  'soda': 'local_drink',
  'tea': 'local_drink',
  
  // Ferramentas e Utilitários
  'hammer': 'build',
  'wrench': 'build',
  'screwdriver': 'build',
  'saw': 'build',
  'drill': 'build',
  'screw': 'build',
  'nail': 'build',
  'bolt': 'build',
  'nut': 'build',
  'washer': 'build',
  'ruler': 'straighten',
  'tape-measure': 'straighten',
  'level': 'straighten',
  'compass': 'explore',
  'magnifying-glass': 'search',
  'microscope': 'biotech',
  'telescope': 'biotech',
  'binoculars': 'biotech',
  'camera': 'camera_alt',
  'video': 'videocam',
  'phone': 'phone',
  'tablet': 'tablet',
  'laptop': 'laptop',
  'desktop': 'desktop_windows',
  'monitor': 'monitor',
  'keyboard': 'keyboard',
  'mouse': 'mouse',
  'printer': 'print',
  'scanner': 'scanner',
  'fax': 'print',
  'copier': 'content_copy',
  
  // Símbolos e Sinais
  'check': 'check',
  'x': 'close',
  'plus': 'add',
  'minus': 'remove',
  'multiply': 'close',
  'divide': 'close',
  'equals': 'drag_indicator',
  'greater-than': 'keyboard_arrow_right',
  'less-than': 'keyboard_arrow_left',
  'percent': 'percent',
  'dollar': 'attach_money',
  'euro': 'euro',
  'pound': 'currency_pound',
  'yen': 'currency_yen',
  'rupee': 'currency_rupee',
  'bitcoin': 'currency_bitcoin',
  'ethereum': 'currency_bitcoin',
  
  // Setas e Direções
  'arrow-up': 'arrow_upward',
  'arrow-down': 'arrow_downward',
  'arrow-left': 'arrow_back',
  'arrow-right': 'arrow_forward',
  'arrow-up-left': 'north_west',
  'arrow-up-right': 'north_east',
  'arrow-down-left': 'south_west',
  'arrow-down-right': 'south_east',
  'chevron-up': 'keyboard_arrow_up',
  'chevron-down': 'keyboard_arrow_down',
  'chevron-left': 'keyboard_arrow_left',
  'chevron-right': 'keyboard_arrow_right',
  'chevron-up-left': 'keyboard_arrow_up',
  'chevron-up-right': 'keyboard_arrow_up',
  'chevron-down-left': 'keyboard_arrow_down',
  'chevron-down-right': 'keyboard_arrow_down',
  
  // Formas Geométricas
  'circle': 'radio_button_unchecked',
  'square': 'crop_square',
  'triangle': 'change_history',
  'diamond': 'diamond',
  'hexagon': 'hexagon',
  'octagon': 'hexagon',
  'pentagon': 'pentagon',
  'star': 'star',
  'heart': 'favorite',
  'spade': 'spade',
  'club': 'club',
  'diamond': 'diamond',
  
  // Cores
  'color': 'palette',
  'paint-bucket': 'format_color_fill',
  'brush': 'format_color_fill',
  'palette': 'palette',
  'droplet': 'water_drop',
  'eyedropper': 'format_color_fill',
  'contrast': 'contrast',
  'brightness': 'brightness_6',
  'saturation': 'tune',
  'hue': 'tune',
  'opacity': 'opacity',
  'gradient': 'gradient',
  'fill': 'format_color_fill',
  'stroke': 'format_color_fill',
  
  // Texto e Tipografia
  'text': 'text_fields',
  'bold': 'format_bold',
  'italic': 'format_italic',
  'underline': 'format_underlined',
  'strikethrough': 'format_strikethrough',
  'align-left': 'format_align_left',
  'align-center': 'format_align_center',
  'align-right': 'format_align_right',
  'align-justify': 'format_align_justify',
  'list': 'format_list_bulleted',
  'list-numbered': 'format_list_numbered',
  'quote': 'format_quote',
  'code': 'code',
  'terminal': 'terminal',
  'command': 'terminal',
  'hash': 'tag',
  'at': 'alternate_email',
  'link': 'link',
  'unlink': 'link_off',
  'external-link': 'open_in_new',
  'mail': 'mail',
  'phone': 'phone',
  'globe': 'language',
  'map': 'map',
  'location': 'location_on',
  'pin': 'room',
  'flag': 'flag',
  'bookmark': 'bookmark',
  'tag': 'local_offer',
  'tags': 'local_offer',
  'folder': 'folder',
  'file': 'description',
  'image': 'image',
  'video': 'videocam',
  'music': 'music_note',
  'volume': 'volume_up',
  'mic': 'mic',
  'camera': 'camera_alt',
  'download': 'download',
  'upload': 'upload',
  'share': 'share',
  'copy': 'content_copy',
  'cut': 'content_cut',
  'paste': 'content_paste',
  'undo': 'undo',
  'redo': 'redo',
  'save': 'save',
  'print': 'print',
  'search': 'search',
  'filter': 'filter_list',
  'sort': 'sort',
  'refresh': 'refresh',
  'loading': 'hourglass_empty',
  'spinner': 'refresh',
  'check': 'check',
  'x': 'close',
  'plus': 'add',
  'minus': 'remove',
  'edit': 'edit',
  'delete': 'delete',
  'trash': 'delete',
  'archive': 'archive',
  'unarchive': 'unarchive',
  'lock': 'lock',
  'unlock': 'lock_open',
  'key': 'vpn_key',
  'shield': 'security',
  'eye': 'visibility',
  'eye-off': 'visibility_off',
  'hide': 'visibility_off',
  'show': 'visibility',
  'settings': 'settings',
  'gear': 'settings',
  'cog': 'settings',
  'wrench': 'build',
  'tool': 'build',
  'hammer': 'build',
  'screwdriver': 'build',
  'drill': 'build',
  'saw': 'build',
  'ruler': 'straighten',
  'level': 'straighten',
  'compass': 'explore',
  'magnifying-glass': 'search',
  'microscope': 'biotech',
  'telescope': 'biotech',
  'binoculars': 'biotech',
  'camera': 'camera_alt',
  'video': 'videocam',
  'phone': 'phone',
  'tablet': 'tablet',
  'laptop': 'laptop',
  'desktop': 'desktop_windows',
  'monitor': 'monitor',
  'keyboard': 'keyboard',
  'mouse': 'mouse',
  'printer': 'print',
  'scanner': 'scanner',
  'fax': 'print',
  'copier': 'content_copy',
  'wifi': 'wifi',
  'bluetooth': 'bluetooth',
  'battery': 'battery_std',
  'power': 'power',
  'plug': 'power',
  'cpu': 'memory',
  'hard-drive': 'storage',
  'database': 'storage',
  'server': 'dns',
  'cloud': 'cloud',
  'cloud-upload': 'cloud_upload',
  'cloud-download': 'cloud_download',
  'cloud-off': 'cloud_off',
  'sync': 'sync',
  'sync-alt': 'sync',
  'rotate': 'rotate_right',
  'flip': 'flip',
  'mirror': 'flip',
  'crop': 'crop',
  'resize': 'open_with',
  'move': 'open_with',
  'drag': 'drag_indicator',
  'grab': 'drag_indicator',
  'hand': 'pan_tool',
  'cursor': 'mouse',
  'pointer': 'mouse',
  'target': 'flag',
  'crosshair': 'gps_fixed',
  'bullseye': 'gps_fixed',
  'focus': 'center_focus_strong',
  'zoom-in': 'zoom_in',
  'zoom-out': 'zoom_out',
  'zoom': 'zoom_in',
  'maximize': 'fullscreen',
  'minimize': 'fullscreen_exit',
  'expand': 'open_in_full',
  'collapse': 'close_fullscreen',
  'resize': 'open_with',
  'move': 'open_with',
  'drag': 'drag_indicator',
  'grab': 'drag_indicator',
  'hand': 'pan_tool',
  'cursor': 'mouse',
  'pointer': 'mouse',
  
  // Ícones adicionais para migração completa
  'lightbulb': 'lightbulb',
  'more-horizontal': 'more_horiz',
  'inbox': 'inbox',
  'check-square': 'check_box',
  'square': 'check_box_outline_blank',
} as const;

export type IconName = keyof typeof IconMapping;

// Componente de ícone Material seguindo WCAG 2.2 AA
interface MaterialIconProps {
  name: IconName;
  size?: number | string;
  className?: string;
  'aria-label'?: string;
  'aria-hidden'?: boolean;
  role?: string;
  fill?: boolean;
  weight?: 100 | 200 | 300 | 400 | 500 | 600 | 700;
  grade?: -25 | 0 | 200;
  opticalSize?: 20 | 24 | 40 | 48;
  color?: string;
  onClick?: () => void;
  onKeyDown?: (e: React.KeyboardEvent) => void;
  tabIndex?: number;
  disabled?: boolean;
  tooltip?: string | boolean; // Descrição do tooltip. Se true, usa aria-label ou gera automaticamente
  tooltipSide?: 'top' | 'bottom' | 'left' | 'right';
  tooltipDelay?: number;
}

export const MaterialIcon: React.FC<MaterialIconProps> = ({
  name,
  size = 24,
  className = '',
  'aria-label': ariaLabel,
  'aria-hidden': ariaHidden = false,
  role,
  fill = false,
  weight = 400,
  grade = 0,
  opticalSize = 24,
  color,
  onClick,
  onKeyDown,
  tabIndex = 0,
  disabled = false,
  tooltip,
  tooltipSide = 'top',
  tooltipDelay = 300,
}) => {
  const iconName = IconMapping[name as keyof typeof IconMapping];
  
  if (!iconName) {
    console.warn(`Icon "${name}" not found in mapping`);
    return null;
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (onKeyDown) {
      onKeyDown(e);
    }
    
    // Suporte a teclado para acessibilidade (WCAG 2.2 AA)
    if (onClick && (e.key === 'Enter' || e.key === ' ')) {
      e.preventDefault();
      onClick();
    }
  };

  const iconStyle = {
    fontSize: typeof size === 'number' ? `${size}px` : size,
    color: color,
    fontVariationSettings: `'FILL' ${fill ? 1 : 0}, 'wght' ${weight}, 'GRAD' ${grade}, 'opsz' ${opticalSize}`,
  };

  const baseClasses = [
    'material-symbols-outlined',
    'inline-flex',
    'items-center',
    'justify-center',
    'select-none',
    'transition-colors',
    'duration-200',
    disabled ? 'opacity-50 cursor-not-allowed' : onClick ? 'cursor-pointer' : '',
    className,
  ].filter(Boolean).join(' ');

  // Determinar o texto do tooltip
  const getTooltipText = (): string | null => {
    // Se tooltip é explicitamente false, não mostrar tooltip
    if (tooltip === false) {
      return null;
    }
    
    // Se tooltip é uma string, usar ela
    if (typeof tooltip === 'string') {
      return tooltip;
    }
    
    // Se tooltip é true ou undefined, usar aria-label ou gerar automaticamente
    if (tooltip === true || tooltip === undefined) {
      // Se há aria-label, usar ele
      if (ariaLabel) {
        return ariaLabel;
      }
      
      // Gerar tooltip automático para todos os ícones (mesmo decorativos)
      // Isso melhora a experiência do usuário ao passar o mouse
      return IconAccessibility.generateAriaLabel(name);
    }
    
    return null;
  };

  const tooltipText = getTooltipText();
  // Mostrar tooltip se houver texto e não foi explicitamente desabilitado
  // Mesmo ícones com aria-hidden="true" podem ter tooltip visual
  const shouldShowTooltip = tooltipText !== null && tooltip !== false;

  const iconElement = (
    <span
      className={baseClasses}
      style={iconStyle}
      aria-label={ariaLabel}
      aria-hidden={ariaHidden}
      role={role || (onClick ? 'button' : undefined)}
      tabIndex={onClick && !disabled ? tabIndex : undefined}
      onClick={disabled ? undefined : onClick}
      onKeyDown={handleKeyDown}
      data-icon={name}
      data-material-icon={iconName}
    >
      {iconName}
    </span>
  );

  // Se deve mostrar tooltip, envolver com Tooltip
  if (shouldShowTooltip) {
    return (
      <TooltipProvider delayDuration={tooltipDelay}>
        <Tooltip>
          <TooltipTrigger asChild>
            {iconElement}
          </TooltipTrigger>
          <TooltipContent side={tooltipSide} sideOffset={4}>
            {tooltipText}
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    );
  }

  return iconElement;
};

// Hook para usar ícones com acessibilidade
export const useMaterialIcon = () => {
  const getIcon = (name: IconName, props?: Partial<MaterialIconProps>) => {
    return <MaterialIcon name={name} {...props} />;
  };

  return { getIcon, MaterialIcon };
};

// Utilitários para acessibilidade
export const IconAccessibility = {
  // Cores contrastantes seguindo WCAG 2.2 AA
  getContrastColor: (backgroundColor: string) => {
    // Implementação simplificada - em produção usar biblioteca de contraste
    const isLight = backgroundColor === 'white' || backgroundColor.includes('light') || backgroundColor.includes('50');
    return isLight ? '#000000' : '#ffffff';
  },
  
  // Tamanhos mínimos para touch targets (WCAG 2.2 AA)
  getMinTouchSize: () => 44, // 44px mínimo para touch targets
  
  // Verificar se ícone precisa de aria-label
  needsAriaLabel: (name: IconName, context?: string) => {
    const decorativeIcons = ['spacer', 'divider', 'separator'];
    return !decorativeIcons.includes(name) && !context;
  },
  
  // Gerar aria-label baseado no contexto
  generateAriaLabel: (name: IconName, context?: string) => {
    const labels: Record<string, string> = {
      'home': 'Ir para página inicial',
      'user': 'Perfil do usuário',
      'settings': 'Configurações',
      'menu': 'Abrir menu',
      'search': 'Pesquisar',
      'filter': 'Filtrar resultados',
      'sort': 'Ordenar',
      'refresh': 'Atualizar',
      'close': 'Fechar',
      'check': 'Confirmar',
      'plus': 'Adicionar',
      'plus-circle': 'Adicionar',
      'minus': 'Remover',
      'edit': 'Editar',
      'delete': 'Excluir',
      'trash': 'Excluir',
      'trash-2': 'Excluir',
      'save': 'Salvar',
      'download': 'Baixar',
      'upload': 'Enviar',
      'copy': 'Copiar',
      'log-out': 'Sair da conta',
      'bell': 'Notificações',
      'alert-triangle': 'Aviso',
      'alert-circle': 'Erro',
      'info': 'Informação',
      'check-circle': 'Sucesso',
      'clock': 'Horário',
      'calendar': 'Calendário',
      'dollar-sign': 'Valor monetário',
      'credit-card': 'Cartão de crédito',
      'wallet': 'Carteira',
      'trending-up': 'Tendência de alta',
      'trending-down': 'Tendência de baixa',
      'chart': 'Gráfico',
      'bar-chart-3': 'Gráfico de barras',
      'pie-chart': 'Gráfico de pizza',
      'brain': 'IA Financeira',
      'accessibility': 'Acessibilidade',
      'mail': 'Email',
      'lock': 'Senha',
      'eye': 'Mostrar',
      'eye-off': 'Ocultar',
      'key': 'Chave',
      'phone': 'Telefone',
      'map-pin': 'Localização',
      'globe': 'Idioma',
      'flag': 'País',
      'play': 'Reproduzir',
      'pause': 'Pausar',
      'stop': 'Parar',
      'skip-forward': 'Avançar',
      'skip-back': 'Voltar',
      'chevron-up': 'Expandir',
      'chevron-down': 'Recolher',
      'chevron-left': 'Anterior',
      'chevron-right': 'Próximo',
      'arrow-up': 'Para cima',
      'arrow-down': 'Para baixo',
      'arrow-left': 'Para esquerda',
      'arrow-right': 'Para direita',
      'file': 'Arquivo',
      'file-text': 'Documento',
      'file-plus': 'Novo arquivo',
      'folder': 'Pasta',
      'folder-plus': 'Nova pasta',
      'folder-open': 'Pasta aberta',
      'archive': 'Arquivo',
      'bookmark': 'Marcador',
      'bookmark-plus': 'Adicionar marcador',
      'message': 'Mensagem',
      'message-circle': 'Chat',
      'send': 'Enviar',
      'reply': 'Responder',
      'share': 'Compartilhar',
      'link': 'Link',
      'loading': 'Carregando',
      'spinner': 'Processando',
      'star': 'Favorito',
      'star-filled': 'Favorito',
      'heart': 'Curtir',
      'heart-filled': 'Curtido',
      'thumbs-up': 'Aprovar',
      'thumbs-down': 'Desaprovar',
      'like': 'Curtir',
      'dislike': 'Não curtir',
      'tag': 'Tag',
      'tags': 'Tags',
      'category': 'Categoria',
      'grid': 'Visualização em grade',
      'list': 'Visualização em lista',
      'layout': 'Layout',
      'columns': 'Colunas',
      'rows': 'Linhas',
      'shield': 'Segurança',
      'shield-check': 'Verificado',
      'shield-alert': 'Alerta de segurança',
      'unlock': 'Desbloquear',
      'fingerprint': 'Biometria',
      'volume': 'Volume',
      'volume-off': 'Sem som',
      'volume-low': 'Volume baixo',
      'volume-high': 'Volume alto',
      'mic': 'Microfone',
      'mic-off': 'Microfone desligado',
      'video': 'Vídeo',
      'video-off': 'Vídeo desligado',
      'camera': 'Câmera',
      'image': 'Imagem',
      'palette': 'Paleta de cores',
      'contrast': 'Contraste',
      'brightness': 'Brilho',
      'help': 'Ajuda',
      'help-circle': 'Ajuda',
      'question': 'Pergunta',
      'more': 'Mais opções',
      'more-vertical': 'Mais opções',
      'dots': 'Mais opções',
      'dots-vertical': 'Mais opções',
      'ellipsis': 'Mais opções',
      'ellipsis-vertical': 'Mais opções',
      'time': 'Tempo',
      'timer': 'Cronômetro',
      'stopwatch': 'Cronômetro',
      'hourglass': 'Tempo esgotado',
      'compass': 'Bússola',
      'navigation': 'Navegação',
      'map': 'Mapa',
      'location': 'Localização',
      'pin': 'Marcador',
      'target': 'Alvo',
      'crosshair': 'Mira',
      'wifi': 'Wi-Fi',
      'wifi-off': 'Wi-Fi desligado',
      'bluetooth': 'Bluetooth',
      'bluetooth-off': 'Bluetooth desligado',
      'battery': 'Bateria',
      'battery-charging': 'Carregando bateria',
      'power': 'Energia',
      'plug': 'Plug',
      'cpu': 'Processador',
      'hard-drive': 'Disco rígido',
      'database': 'Banco de dados',
      'server': 'Servidor',
      'cloud': 'Nuvem',
      'cloud-upload': 'Enviar para nuvem',
      'cloud-download': 'Baixar da nuvem',
      'cloud-off': 'Nuvem desligada',
      'users': 'Usuários',
      'user-plus': 'Adicionar usuário',
      'user-minus': 'Remover usuário',
      'user-check': 'Usuário verificado',
      'user-x': 'Usuário bloqueado',
      'team': 'Equipe',
      'organization': 'Organização',
      'building': 'Empresa',
      'company': 'Empresa',
      'shopping-cart': 'Carrinho de compras',
      'shopping-bag': 'Sacola de compras',
      'store': 'Loja',
      'shop': 'Loja',
      'barcode': 'Código de barras',
      'qr-code': 'Código QR',
      'price-tag': 'Preço',
      'discount': 'Desconto',
      'percent': 'Porcentagem',
      'gift': 'Presente',
      'truck': 'Entrega',
      'package': 'Pacote',
      'box': 'Caixa',
      'book': 'Livro',
      'book-open': 'Livro aberto',
      'graduation-cap': 'Formação',
      'award': 'Prêmio',
      'certificate': 'Certificado',
      'trophy': 'Troféu',
      'medal': 'Medalha',
      'badge': 'Distintivo',
      'heart': 'Coração',
      'heartbeat': 'Batimento cardíaco',
      'activity': 'Atividade',
      'pulse': 'Pulso',
      'lightbulb': 'Ideia',
      'more-horizontal': 'Mais opções',
      'inbox': 'Caixa de entrada',
      'check-square': 'Selecionar todos',
      'square': 'Desselecionar',
      'thermometer': 'Termômetro',
      'droplet': 'Gota',
      'pill': 'Medicamento',
      'syringe': 'Seringa',
      'stethoscope': 'Estetoscópio',
      'cross': 'Cruz médica',
      'gamepad': 'Controle de jogo',
      'controller': 'Controle',
      'football': 'Futebol',
      'basketball': 'Basquete',
      'tennis': 'Tênis',
      'golf': 'Golfe',
      'swimming': 'Natação',
      'running': 'Corrida',
      'cycling': 'Ciclismo',
      'hiking': 'Caminhada',
      'music': 'Música',
      'repeat': 'Repetir',
      'shuffle': 'Embaralhar',
      'headphones': 'Fones de ouvido',
      'speaker': 'Alto-falante',
      'house': 'Casa',
      'door': 'Porta',
      'window': 'Janela',
      'bed': 'Cama',
      'bath': 'Banheiro',
      'kitchen': 'Cozinha',
      'living-room': 'Sala de estar',
      'garage': 'Garagem',
      'garden': 'Jardim',
      'pool': 'Piscina',
      'car': 'Carro',
      'bus': 'Ônibus',
      'train': 'Trem',
      'plane': 'Avião',
      'ship': 'Navio',
      'bike': 'Bicicleta',
      'motorcycle': 'Moto',
      'taxi': 'Táxi',
      'subway': 'Metrô',
      'sun': 'Sol',
      'moon': 'Lua',
      'cloud-rain': 'Chuva',
      'cloud-snow': 'Neve',
      'cloud-lightning': 'Raio',
      'wind': 'Vento',
      'snowflake': 'Floco de neve',
      'umbrella': 'Guarda-chuva',
      'tree': 'Árvore',
      'flower': 'Flor',
      'leaf': 'Folha',
      'mountain': 'Montanha',
      'waves': 'Ondas',
      'coffee': 'Café',
      'wine': 'Vinho',
      'beer': 'Cerveja',
      'cake': 'Bolo',
      'pizza': 'Pizza',
      'hamburger': 'Hambúrguer',
      'ice-cream': 'Sorvete',
      'apple': 'Maçã',
      'banana': 'Banana',
      'carrot': 'Cenoura',
      'bread': 'Pão',
      'fish': 'Peixe',
      'chicken': 'Frango',
      'beef': 'Carne',
      'egg': 'Ovo',
      'milk': 'Leite',
      'water': 'Água',
      'juice': 'Suco',
      'soda': 'Refrigerante',
      'tea': 'Chá',
      'hammer': 'Martelo',
      'wrench': 'Chave',
      'screwdriver': 'Chave de fenda',
      'saw': 'Serra',
      'drill': 'Furadeira',
      'screw': 'Parafuso',
      'bolt': 'Parafuso',
      'nut': 'Porca',
      'washer': 'Arruela',
      'ruler': 'Régua',
      'tape-measure': 'Fita métrica',
      'level': 'Nível',
      'compass': 'Bússola',
      'magnifying-glass': 'Lupa',
      'microscope': 'Microscópio',
      'telescope': 'Telescópio',
      'binoculars': 'Binóculos',
      'tablet': 'Tablet',
      'laptop': 'Laptop',
      'desktop': 'Desktop',
      'monitor': 'Monitor',
      'keyboard': 'Teclado',
      'mouse': 'Mouse',
      'printer': 'Impressora',
      'scanner': 'Scanner',
      'fax': 'Fax',
      'copier': 'Copiadora',
      'sync': 'Sincronizar',
      'sync-alt': 'Sincronizar',
      'rotate': 'Rotacionar',
      'flip': 'Virar',
      'mirror': 'Espelhar',
      'crop': 'Cortar',
      'resize': 'Redimensionar',
      'move': 'Mover',
      'drag': 'Arrastar',
      'grab': 'Agarrar',
      'hand': 'Mão',
      'cursor': 'Cursor',
      'pointer': 'Ponteiro',
      'bullseye': 'Alvo',
      'focus': 'Focar',
      'zoom-in': 'Aumentar zoom',
      'zoom-out': 'Diminuir zoom',
      'zoom': 'Zoom',
      'maximize': 'Maximizar',
      'minimize': 'Minimizar',
      'expand': 'Expandir',
      'collapse': 'Recolher',
      'circle': 'Círculo',
      'square': 'Quadrado',
      'triangle': 'Triângulo',
      'diamond': 'Diamante',
      'hexagon': 'Hexágono',
      'octagon': 'Octógono',
      'pentagon': 'Pentágono',
      'star': 'Estrela',
      'spade': 'Espadas',
      'club': 'Paus',
      'diamond': 'Ouros',
      'color': 'Cor',
      'paint-bucket': 'Balde de tinta',
      'brush': 'Pincel',
      'droplet': 'Gota',
      'eyedropper': 'Conta-gotas',
      'saturation': 'Saturação',
      'hue': 'Matiz',
      'opacity': 'Opacidade',
      'gradient': 'Gradiente',
      'fill': 'Preenchimento',
      'stroke': 'Contorno',
      'text': 'Texto',
      'bold': 'Negrito',
      'italic': 'Itálico',
      'underline': 'Sublinhado',
      'strikethrough': 'Riscado',
      'align-left': 'Alinhar à esquerda',
      'align-center': 'Centralizar',
      'align-right': 'Alinhar à direita',
      'align-justify': 'Justificar',
      'list-numbered': 'Lista numerada',
      'quote': 'Citação',
      'code': 'Código',
      'terminal': 'Terminal',
      'command': 'Comando',
      'hash': 'Hashtag',
      'at': 'Arroba',
      'unlink': 'Desvincular',
      'external-link': 'Link externo',
      'cut': 'Cortar',
      'paste': 'Colar',
      'undo': 'Desfazer',
      'redo': 'Refazer',
      'print': 'Imprimir',
      'unarchive': 'Desarquivar',
      'archive': 'Arquivar',
      'gear': 'Engrenagem',
      'cog': 'Engrenagem',
      'tool': 'Ferramenta',
      'screw': 'Parafuso',
      'nail': 'Prego',
      'bolt': 'Parafuso',
      'nut': 'Porca',
      'washer': 'Arruela',
      'straighten': 'Endireitar',
      'biotech': 'Biotecnologia',
      'memory': 'Memória',
      'storage': 'Armazenamento',
      'dns': 'DNS',
      'cloud_upload': 'Enviar para nuvem',
      'cloud_download': 'Baixar da nuvem',
      'cloud_off': 'Nuvem desligada',
      'rotate_right': 'Rotacionar à direita',
      'open_with': 'Abrir com',
      'drag_indicator': 'Indicador de arrastar',
      'pan_tool': 'Ferramenta de pan',
      'gps_fixed': 'GPS fixo',
      'center_focus_strong': 'Foco central forte',
      'fullscreen': 'Tela cheia',
      'fullscreen_exit': 'Sair da tela cheia',
      'open_in_full': 'Abrir em tela cheia',
      'close_fullscreen': 'Fechar tela cheia',
    };
    
    return labels[name] || context || `Ícone ${name}`;
  },
};

export default MaterialIcon;
